version: '3'
services:
  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
      MINIO_DEFAULT_BUCKETS: 'bank.search.test'
    command: server --address "0.0.0.0:9099" --console-address "0.0.0.0:9000" /data